server:
  port: 8090

spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/SMH
    username: postgres
    password: 1234
    
mybatis:
  mapper-locations: classpath:mappers/*/*.xml
  configuration:
    map-underscore-to-camel-case: true

