jwt:
  secretKey : leebeomjunleebeomjunleebeomjunleebeomjunleebeomjunleebeomjunLdadqwdadadDqsdad231DAdqladadadadadadadlvqdqddadsa
  accessToken-valid-seconds : 600
  refreshToken-valid-seconds : 86400
#  600 #86400
  
weather:
  secretKey: 8f3f7b217f784989c575f5f9e6a7b37b
  
recaptcha:
  secretKey: 6LdJJYsoAAAAANh0NN7YQhDlUUeQO30YpfBeGB_B
  url: https://www.google.com/recaptcha/api/siteverify
  
cafe24:
  id: thalsghks
  secretKey: a7df2ef01970f20ed87a0051f81592ff
  url: https://sslsms.cafe24.com/sms_sender.php