jwt:
  secretKey : leebeomjunleebeomjunleebeomjunleebeomjunleebeomjunleebeomjunLdadqwdadadDqsdad231DAdqladadadadadadadlvqdqddadsa
  accessToken-valid-seconds : 600
  refreshToken-valid-seconds : 86400
#  600 #86400
  
weather:
  secretKey: 8f3f7b217f784989c575f5f9e6a7b37b
  
recaptcha:
  secretKey: 6LdJJYsoAAAAANh0NN7YQhDlUUeQO30YpfBeGB_B
  url: https://www.google.com/recaptcha/api/siteverify